try:
    from anki.lang import current_lang
except:
    current_lang = "en"

# Languages commonly used in Anki
# ENGLISH_EN = "en"
# JAPANESE_JA = "ja"
# PORTUGUESE_PT = "pt"
# GERMAN_DE = "de"
# FRENCH_FR = "fr"
# PERSIAN_FA = "fa"
# RUSSIAN_RU = "ru"
# SPANISH_ES = "es"
# VIETNAMESE_VI = "vi"

#--------------

ENGLISH_EN = "en"
JAPANESE_JA = "ja"
PORTUGUES_PT = "pt"
DEUTSCH_DE = "de"
FRANCAIS_FR = "fr"
PERSIAN_FA = "fa"
RUSSIAN_RU = "ru"
ESPANOL_ES = "es"
TIENG_VIET_VI = "vi"
# -----------
AFRIKAANS_AF = "af"
BAHASA_MELAYU_MS = "ms"
CATALA_CA = "ca"
DANSK_DA = "da"
EESTI_ET = "et"
ESPERANTO_EO = "eo"
EUSKARA_EU = "eu"
GALEGO_GL = "gl"
HRVATSKI_HR = "hr"
ITALIANO_IT = "it"
LO_JBOBAU_JBO = "jbo"
LENGA_DOC_OC = "oc"
MAGYAR_HU = "hu"
NEDERLANDS_NL = "nl"
NORSK_NB = "nb"
POLSKI_PL = "pl"
ROMANA_RO = "ro"
SLOVENCINA_SK = "sk"
SLOVENSCINA_SL = "sl"
SUOMI_FI = "fi"
SVENSKA_SV = "sv"
TURKCE_TR = "tr"
SIMPLIFIED_CHINESE_ZH = "zh"
KOREAN_KO = "ko"
CESTINA_CS = "cs"
HELLENIC_EL = "el"
BULGARIAN_BG = "bg"
MONGOL_MN = "mn"
SERBIAN_SR = "sr"
UKRAINIAN_UK = "uk"
ARMENIAN_HY = "hy"
HEBREW_HE = "he"
ARABIC_AR = "ar"
THAI_TH = "th"
LATIN_LA = "la"
IRISH_GA = "ga"
BELARUSIAN_BE = "be"
ODIA_OR = "or"
FILIPINO_TL = "tl"


qtip_style = """
    QToolTip {
        border: 1px solid black;
        padding: 5px;
        font-size: 2em;
        background-color: #303030;
        color: white;
    }
"""


"""
 = {
        ENGLISH_EN : "",
        JAPANESE_JA : "",
        PORTUGUES_PT : "",
        DEUTSCH_DE : "",
        FRANCAIS_FR : "",
        PERSIAN_FA : "",
        RUSSIAN_RU : "",
        ESPANOL_ES : "",
        TIENG_VIET_VI : "",
        # ---------
        AFRIKAANS_AF : "",
        BAHASA_MELAYU_MS : "",
        CATALA_CA : "",
        DANSK_DA : "",
        EESTI_ET : "",
        ESPERANTO_EO : "",
        EUSKARA_EU : "",
        GALEGO_GL : "",
        HRVATSKI_HR : "",
        ITALIANO_IT : "",
        LO_JBOBAU_JBO : "",
        LENGA_DOC_OC : "",
        MAGYAR_HU : "",
        NEDERLANDS_NL : "",
        NORSK_NB : "",
        POLSKI_PL : "",
        ROMANA_RO : "",
        SLOVENCINA_SK : "",
        SLOVENSCINA_SL : "",
        SUOMI_FI : "",
        SVENSKA_SV : "",
        TURKCE_TR : "",
        SIMPLIFIED_CHINESE_ZH : "",
        KOREAN_KO : "",
        CESTINA_CS : "",
        HELLENIC_EL : "",
        BULGARIAN_BG : "",
        MONGOL_MN : "",
        SERBIAN_SR : "",
        UKRAINIAN_UK : "",
        ARMENIAN_HY : "",
        HEBREW_HE : "",
        ARABIC_AR : "",
        THAI_TH : "",
        LATIN_LA : "",
        IRISH_GA : "",
        BELARUSIAN_BE : "",
        ODIA_OR : "",
        FILIPINO_TL : "",
        }
"""
"""
の中にあるすべての空の辞書の値に各言語の翻訳を追加
"""


class LanguageManager:

    def __init__(s):

        s.send_prompt = {
            ENGLISH_EN : "Send Prompt",
            JAPANESE_JA : "プロンプトを送信",
            PORTUGUES_PT : "Enviar Prompt",
            DEUTSCH_DE : "Prompt senden",
            FRANCAIS_FR : "Envoyer le prompt",
            PERSIAN_FA : "ارسال پیام",
            RUSSIAN_RU : "Отправить запрос",
            ESPANOL_ES : "Enviar indicación",
            TIENG_VIET_VI : "Gửi lời nhắc",
            # ---------
            AFRIKAANS_AF : "Stuur Aanwysing",
            BAHASA_MELAYU_MS : "Hantar Petunjuk",
            CATALA_CA : "Enviar Prompt",
            DANSK_DA : "Send Prompt",
            EESTI_ET : "Saada vihje",
            ESPERANTO_EO : "Sendi Indikon",
            EUSKARA_EU : "Bidali Oharra",
            GALEGO_GL : "Enviar Prompt",
            HRVATSKI_HR : "Pošalji uputu",
            ITALIANO_IT : "Invia Prompt",
            LO_JBOBAU_JBO : "Send Prompt",
            LENGA_DOC_OC : "Invia Prompt",
            MAGYAR_HU : "Küldés Utasítás",
            NEDERLANDS_NL : "Stuur Prompt",
            NORSK_NB : "Send Prompt",
            POLSKI_PL : "Wyślij Prompt",
            ROMANA_RO : "Trimite Prompt",
            SLOVENCINA_SK : "Poslať Pokyn",
            SLOVENSCINA_SL : "Pošlji Navodilo",
            SUOMI_FI : "Lähetä Ohje",
            SVENSKA_SV : "Skicka Prompt",
            TURKCE_TR : "Gönder İpucu",
            SIMPLIFIED_CHINESE_ZH : "发送提示",
            KOREAN_KO : "프롬프트 보내기",
            CESTINA_CS : "Poslat Prompt",
            HELLENIC_EL : "Αποστολή Υπόδειξης",
            BULGARIAN_BG : "Изпрати Подсказка",
            MONGOL_MN : "Илгээх Зөвлөгөө",
            SERBIAN_SR : "Пошаљи Упутство",
            UKRAINIAN_UK : "Надіслати Підказку",
            ARMENIAN_HY : "Ուղարկել Հրահանգը",
            HEBREW_HE : "שלח הזמנה",
            ARABIC_AR : "إرسال الإرشاد",
            THAI_TH : "ส่งคำแนะนำ",
            LATIN_LA : "Mittere Prompt",
            IRISH_GA : "Seol Teachtaireacht",
            BELARUSIAN_BE : "Адправіць Падказку",
            ODIA_OR : "ପଠାନ୍ତ୍ର ପଠାନ୍ତ୍ର",
            FILIPINO_TL : "Ipadala ang Prompt",
        }


        s.OK = {
            ENGLISH_EN : "OK",
            JAPANESE_JA : "決定",
            PORTUGUES_PT : "OK",
            DEUTSCH_DE : "OK",
            FRANCAIS_FR : "OK",
            PERSIAN_FA : "OK",
            RUSSIAN_RU : "OK",
            ESPANOL_ES : "OK",
            TIENG_VIET_VI : "OK",
            # ---------
            AFRIKAANS_AF : "OK",
            BAHASA_MELAYU_MS : "OK",
            CATALA_CA : "OK",
            DANSK_DA : "OK",
            EESTI_ET : "OK",
            ESPERANTO_EO : "OK",
            EUSKARA_EU : "OK",
            GALEGO_GL : "OK",
            HRVATSKI_HR : "OK",
            ITALIANO_IT : "OK",
            LO_JBOBAU_JBO : "OK",
            LENGA_DOC_OC : "OK",
            MAGYAR_HU : "OK",
            NEDERLANDS_NL : "OK",
            NORSK_NB : "OK",
            POLSKI_PL : "OK",
            ROMANA_RO : "OK",
            SLOVENCINA_SK : "OK",
            SLOVENSCINA_SL : "OK",
            SUOMI_FI : "OK",
            SVENSKA_SV : "OK",
            TURKCE_TR : "OK",
            SIMPLIFIED_CHINESE_ZH : "OK",
            KOREAN_KO : "OK",
            CESTINA_CS : "OK",
            HELLENIC_EL : "OK",
            BULGARIAN_BG : "OK",
            MONGOL_MN : "OK",
            SERBIAN_SR : "OK",
            UKRAINIAN_UK : "OK",
            ARMENIAN_HY : "OK",
            HEBREW_HE : "OK",
            ARABIC_AR : "OK",
            THAI_TH : "OK",
            LATIN_LA : "OK",
            IRISH_GA : "OK",
            BELARUSIAN_BE : "OK",
            ODIA_OR : "OK",
            FILIPINO_TL : "OK",
        }


        s.Cancel = {
            ENGLISH_EN : "Cancel",
            JAPANESE_JA : "キャンセル",
            PORTUGUES_PT : "Cancelar",
            DEUTSCH_DE : "Abbrechen",
            FRANCAIS_FR : "Annuler",
            PERSIAN_FA : "لغو",
            RUSSIAN_RU : "Отмена",
            ESPANOL_ES : "Cancelar",
            TIENG_VIET_VI : "Hủy",
            # ---------
            AFRIKAANS_AF : "Kanselleer",
            BAHASA_MELAYU_MS : "Batal",
            CATALA_CA : "Cancel·lar",
            DANSK_DA : "Annuller",
            EESTI_ET : "Tühista",
            ESPERANTO_EO : "Nuligi",
            EUSKARA_EU : "Ezeztatu",
            GALEGO_GL : "Cancelar",
            HRVATSKI_HR : "Odustani",
            ITALIANO_IT : "Annulla",
            LO_JBOBAU_JBO : "Cancel",
            LENGA_DOC_OC : "Annulla",
            MAGYAR_HU : "Mégsem",
            NEDERLANDS_NL : "Annuleren",
            NORSK_NB : "Avbryt",
            POLSKI_PL : "Anuluj",
            ROMANA_RO : "Anulează",
            SLOVENCINA_SK : "Zrušiť",
            SLOVENSCINA_SL : "Prekliči",
            SUOMI_FI : "Peruuta",
            SVENSKA_SV : "Avbryt",
            TURKCE_TR : "İptal",
            SIMPLIFIED_CHINESE_ZH : "取消",
            KOREAN_KO : "취소",
            CESTINA_CS : "Zrušit",
            HELLENIC_EL : "Ακύρωση",
            BULGARIAN_BG : "Отказ",
            MONGOL_MN : "Цуцлах",
            SERBIAN_SR : "Откажи",
            UKRAINIAN_UK : "Скасувати",
            ARMENIAN_HY : "Չեղարկել",
            HEBREW_HE : "ביטול",
            ARABIC_AR : "إلغاء",
            THAI_TH : "ยกเลิก",
            LATIN_LA : "Cancellare",
            IRISH_GA : "Cealaigh",
            BELARUSIAN_BE : "Адмяніць",
            ODIA_OR : "ରଦ୍ଦ କରନ୍ତୁ",
            FILIPINO_TL : "Kanselahin",
        }


        s.Fields = {
            ENGLISH_EN : "Fields",
            JAPANESE_JA : "フィールド",
            PORTUGUES_PT : "Campos",
            DEUTSCH_DE : "Felder",
            FRANCAIS_FR : "Champs",
            PERSIAN_FA : "فیلدها",
            RUSSIAN_RU : "Поля",
            ESPANOL_ES : "Campos",
            TIENG_VIET_VI : "Trường",
            # ---------
            AFRIKAANS_AF : "Velde",
            BAHASA_MELAYU_MS : "Medan",
            CATALA_CA : "Camps",
            DANSK_DA : "Felter",
            EESTI_ET : "Väljad",
            ESPERANTO_EO : "Kampoj",
            EUSKARA_EU : "Eremuak",
            GALEGO_GL : "Campos",
            HRVATSKI_HR : "Polja",
            ITALIANO_IT : "Campi",
            LO_JBOBAU_JBO : "Fields",
            LENGA_DOC_OC : "Campi",
            MAGYAR_HU : "Mezők",
            NEDERLANDS_NL : "Velden",
            NORSK_NB : "Felter",
            POLSKI_PL : "Pola",
            ROMANA_RO : "Câmpuri",
            SLOVENCINA_SK : "Polia",
            SLOVENSCINA_SL : "Polja",
            SUOMI_FI : "Kentät",
            SVENSKA_SV : "Fält",
            TURKCE_TR : "Alanlar",
            SIMPLIFIED_CHINESE_ZH : "字段",
            KOREAN_KO : "필드",
            CESTINA_CS : "Pole",
            HELLENIC_EL : "Πεδία",
            BULGARIAN_BG : "Полета",
            MONGOL_MN : "Талбарууд",
            SERBIAN_SR : "Поља",
            UKRAINIAN_UK : "Поля",
            ARMENIAN_HY : "Դաշտեր",
            HEBREW_HE : "שדות",
            ARABIC_AR : "الحقول",
            THAI_TH : "ฟิลด์",
            LATIN_LA : "Campos",
            IRISH_GA : "Réimseanna",
            BELARUSIAN_BE : "Поля",
            ODIA_OR : "କ୍ଷେତ୍ରଗୁଡ଼ିକ",
            FILIPINO_TL : "Mga Larangan",
        }

        s.Credit = {
            ENGLISH_EN : "Credit",
            JAPANESE_JA : "クレジット",
            PORTUGUES_PT : "Crédito",
            DEUTSCH_DE : "Kredit",
            FRANCAIS_FR : "Crédit",
            PERSIAN_FA : "اعتبار",
            RUSSIAN_RU : "Кредит",
            ESPANOL_ES : "Crédito",
            TIENG_VIET_VI : "Tín dụng",
            # ---------
            AFRIKAANS_AF : "Krediet",
            BAHASA_MELAYU_MS : "Kredit",
            CATALA_CA : "Crèdit",
            DANSK_DA : "Kredit",
            EESTI_ET : "Krediit",
            ESPERANTO_EO : "Kredito",
            EUSKARA_EU : "Kreditua",
            GALEGO_GL : "Crédito",
            HRVATSKI_HR : "Kredit",
            ITALIANO_IT : "Credito",
            LO_JBOBAU_JBO : "Credit",
            LENGA_DOC_OC : "Credito",
            MAGYAR_HU : "Hitel",
            NEDERLANDS_NL : "Krediet",
            NORSK_NB : "Kreditt",
            POLSKI_PL : "Kredyt",
            ROMANA_RO : "Credit",
            SLOVENCINA_SK : "Kredit",
            SLOVENSCINA_SL : "Kredit",
            SUOMI_FI : "Luotto",
            SVENSKA_SV : "Kredit",
            TURKCE_TR : "Kredi",
            SIMPLIFIED_CHINESE_ZH : "信用",
            KOREAN_KO : "신용",
            CESTINA_CS : "Kredit",
            HELLENIC_EL : "Πίστωση",
            BULGARIAN_BG : "Кредит",
            MONGOL_MN : "Кредит",
            SERBIAN_SR : "Кредит",
            UKRAINIAN_UK : "Кредит",
            ARMENIAN_HY : "Բանկային գումար",
            HEBREW_HE : "אשראי",
            ARABIC_AR : "ائتمان",
            THAI_TH : "เครดิต",
            LATIN_LA : "Creditum",
            IRISH_GA : "Creidmheas",
            BELARUSIAN_BE : "Крэдыт",
            ODIA_OR : "କ୍ରେଡିଟ୍",
            FILIPINO_TL : "Kredito",
        }

        s.Other = {
            ENGLISH_EN : "Other",
            JAPANESE_JA : "その他",
            PORTUGUES_PT : "Outro",
            DEUTSCH_DE : "Andere",
            FRANCAIS_FR : "Autre",
            PERSIAN_FA : "دیگر",
            RUSSIAN_RU : "Другое",
            ESPANOL_ES : "Otro",
            TIENG_VIET_VI : "Khác",
            # ---------
            AFRIKAANS_AF : "Ander",
            BAHASA_MELAYU_MS : "Lain",
            CATALA_CA : "Altres",
            DANSK_DA : "Andet",
            EESTI_ET : "Muu",
            ESPERANTO_EO : "Alia",
            EUSKARA_EU : "Besteak",
            GALEGO_GL : "Outro",
            HRVATSKI_HR : "Drugo",
            ITALIANO_IT : "Altro",
            LO_JBOBAU_JBO : "drata",
            LENGA_DOC_OC : "Autre",
            MAGYAR_HU : "Egyéb",
            NEDERLANDS_NL : "Anders",
            NORSK_NB : "Annet",
            POLSKI_PL : "Inne",
            ROMANA_RO : "Altul",
            SLOVENCINA_SK : "Iné",
            SLOVENSCINA_SL : "Drugo",
            SUOMI_FI : "Muu",
            SVENSKA_SV : "Annat",
            TURKCE_TR : "Diğer",
            SIMPLIFIED_CHINESE_ZH : "其他",
            KOREAN_KO : "기타",
            CESTINA_CS : "Jiný",
            HELLENIC_EL : "Άλλο",
            BULGARIAN_BG : "Друго",
            MONGOL_MN : "Бусад",
            SERBIAN_SR : "Друго",
            UKRAINIAN_UK : "Інше",
            ARMENIAN_HY : "Այլ",
            HEBREW_HE : "אחר",
            ARABIC_AR : "آخر",
            THAI_TH : "อื่น ๆ",
            LATIN_LA : "Alius",
            IRISH_GA : "Eile",
            BELARUSIAN_BE : "Іншы",
            ODIA_OR : "ଅନ୍ୟ",
            FILIPINO_TL : "Iba",
        }



        s.Exclude = {
            ENGLISH_EN : "Exclude",
            JAPANESE_JA : "除外",
            PORTUGUES_PT : "Excluir",
            DEUTSCH_DE : "Ausschließen",
            FRANCAIS_FR : "Exclure",
            PERSIAN_FA : "مستثنی کردن",
            RUSSIAN_RU : "Исключить",
            ESPANOL_ES : "Excluir",
            TIENG_VIET_VI : "Loại trừ",
            # ---------
            AFRIKAANS_AF : "Uitsluit",
            BAHASA_MELAYU_MS : "Kecualikan",
            CATALA_CA : "Excloure",
            DANSK_DA : "Ekskluder",
            EESTI_ET : "Välja arvata",
            ESPERANTO_EO : "Ekskluzivi",
            EUSKARA_EU : "Ez inkluditu",
            GALEGO_GL : "Excluír",
            HRVATSKI_HR : "Isključiti",
            ITALIANO_IT : "Escludere",
            LO_JBOBAU_JBO : "no'e",
            LENGA_DOC_OC : "Exclure",
            MAGYAR_HU : "Kizár",
            NEDERLANDS_NL : "Uitsluiten",
            NORSK_NB : "Ekskluder",
            POLSKI_PL : "Wyklucz",
            ROMANA_RO : "Exclude",
            SLOVENCINA_SK : "Vylúčiť",
            SLOVENSCINA_SL : "Izključi",
            SUOMI_FI : "Poissulkea",
            SVENSKA_SV : "Exkludera",
            TURKCE_TR : "Hariç tut",
            SIMPLIFIED_CHINESE_ZH : "排除",
            KOREAN_KO : "제외",
            CESTINA_CS : "Vyloučit",
            HELLENIC_EL : "Αποκλείω",
            BULGARIAN_BG : "Изключи",
            MONGOL_MN : "Хасах",
            SERBIAN_SR : "Искључи",
            UKRAINIAN_UK : "Виключити",
            ARMENIAN_HY : "Անջատել",
            HEBREW_HE : "לְהַחֲרִיב",
            ARABIC_AR : "استبعد",
            THAI_TH : "ยกเว้น",
            LATIN_LA : "Excludere",
            IRISH_GA : "Aschur amach",
            BELARUSIAN_BE : "Выключыць",
            ODIA_OR : "ବାହାରକରିବା",
            FILIPINO_TL : "I-exclude",
        }

        s.Always = {
            ENGLISH_EN : "Always",
            JAPANESE_JA : "いつも",
            PORTUGUES_PT : "Sempre",
            DEUTSCH_DE : "Immer",
            FRANCAIS_FR : "Toujours",
            PERSIAN_FA : "همیشه",
            RUSSIAN_RU : "Всегда",
            ESPANOL_ES : "Siempre",
            TIENG_VIET_VI : "Luôn luôn",
            # ---------
            AFRIKAANS_AF : "Altyd",
            BAHASA_MELAYU_MS : "Sentiasa",
            CATALA_CA : "Sempre",
            DANSK_DA : "Altid",
            EESTI_ET : "Alati",
            ESPERANTO_EO : "Ĉiam",
            EUSKARA_EU : "Betiko",
            GALEGO_GL : "Sempre",
            HRVATSKI_HR : "Uvijek",
            ITALIANO_IT : "Sempre",
            LO_JBOBAU_JBO : "jbobau",
            LENGA_DOC_OC : "Sempre",
            MAGYAR_HU : "Mindig",
            NEDERLANDS_NL : "Altijd",
            NORSK_NB : "Alltid",
            POLSKI_PL : "Zawsze",
            ROMANA_RO : "Mereu",
            SLOVENCINA_SK : "Vždy",
            SLOVENSCINA_SL : "Vedno",
            SUOMI_FI : "Aina",
            SVENSKA_SV : "Alltid",
            TURKCE_TR : "Her zaman",
            SIMPLIFIED_CHINESE_ZH : "始终",
            KOREAN_KO : "항상",
            CESTINA_CS : "Vždy",
            HELLENIC_EL : "Πάντα",
            BULGARIAN_BG : "Винаги",
            MONGOL_MN : "Төгсгөлд",
            SERBIAN_SR : "Увек",
            UKRAINIAN_UK : "Завжди",
            ARMENIAN_HY : "Միշտ",
            HEBREW_HE : "תמיד",
            ARABIC_AR : "دائما",
            THAI_TH : "เสมอ",
            LATIN_LA : "Semper",
            IRISH_GA : "I gcónaí",
            BELARUSIAN_BE : "Заўсёды",
            ODIA_OR : "ପ୍ରତିକ୍ଷେତ୍ର",
            FILIPINO_TL : "Laging",
        }




        s.option = {
            ENGLISH_EN: "option",
            JAPANESE_JA: "設定",
            PORTUGUES_PT: "opção",
            DEUTSCH_DE: "Option",
            FRANCAIS_FR: "option",
            PERSIAN_FA: "گزینه",
            RUSSIAN_RU: "опция",
            ESPANOL_ES: "opción",
            TIENG_VIET_VI: "tùy chọn",
            # ---------
            AFRIKAANS_AF: "opsie",
            BAHASA_MELAYU_MS: "pilihan",
            CATALA_CA: "opció",
            DANSK_DA: "mulighed",
            EESTI_ET: "valik",
            ESPERANTO_EO: "opcio",
            EUSKARA_EU: "aukera",
            GALEGO_GL: "opción",
            HRVATSKI_HR: "opcija",
            ITALIANO_IT: "opzione",
            LO_JBOBAU_JBO: "jbobau",
            LENGA_DOC_OC: "opció",
            MAGYAR_HU: "lehetőség",
            NEDERLANDS_NL: "optie",
            NORSK_NB: "alternativ",
            POLSKI_PL: "opcja",
            ROMANA_RO: "opțiune",
            SLOVENCINA_SK: "možnosť",
            SLOVENSCINA_SL: "možnost",
            SUOMI_FI: "vaihtoehto",
            SVENSKA_SV: "alternativ",
            TURKCE_TR: "seçenek",
            SIMPLIFIED_CHINESE_ZH: "选项",
            KOREAN_KO: "옵션",
            CESTINA_CS: "možnost",
            HELLENIC_EL: "επιλογή",
            BULGARIAN_BG: "опция",
            MONGOL_MN: "сонголт",
            SERBIAN_SR: "opcija",
            UKRAINIAN_UK: "опція",
            ARMENIAN_HY: "ընտրանք",
            HEBREW_HE: "אפשרות",
            ARABIC_AR: "خيار",
            THAI_TH: "ตัวเลือก",
            LATIN_LA: "optio",
            IRISH_GA: "rogha",
            BELARUSIAN_BE: "варыянт",
            ODIA_OR: "ବିକଳ୍ପ",
            FILIPINO_TL: "pagpipilian",
        }

        s.Result = {
            ENGLISH_EN: "Result",
            JAPANESE_JA: "結果",
            PORTUGUES_PT: "Resultado",
            DEUTSCH_DE: "Ergebnis",
            FRANCAIS_FR: "Résultat",
            PERSIAN_FA: "نتیجه",
            RUSSIAN_RU: "Результат",
            ESPANOL_ES: "Resultado",
            TIENG_VIET_VI: "Kết quả",
            # ---------
            AFRIKAANS_AF: "Resultaat",
            BAHASA_MELAYU_MS: "Keputusan",
            CATALA_CA: "Resultat",
            DANSK_DA: "Resultat",
            EESTI_ET: "Tulemus",
            ESPERANTO_EO: "Rezulto",
            EUSKARA_EU: "Emaitza",
            GALEGO_GL: "Resultado",
            HRVATSKI_HR: "Rezultat",
            ITALIANO_IT: "Risultato",
            LO_JBOBAU_JBO: "Result",
            LENGA_DOC_OC: "Rezultato",
            MAGYAR_HU: "Eredmény",
            NEDERLANDS_NL: "Resultaat",
            NORSK_NB: "Resultat",
            POLSKI_PL: "Wynik",
            ROMANA_RO: "Rezultat",
            SLOVENCINA_SK: "Výsledok",
            SLOVENSCINA_SL: "Rezultat",
            SUOMI_FI: "Tulos",
            SVENSKA_SV: "Resultat",
            TURKCE_TR: "Sonuç",
            SIMPLIFIED_CHINESE_ZH: "结果",
            KOREAN_KO: "결과",
            CESTINA_CS: "Výsledek",
            HELLENIC_EL: "Αποτέλεσμα",
            BULGARIAN_BG: "Резултат",
            MONGOL_MN: "Үр дүн",
            SERBIAN_SR: "Резултат",
            UKRAINIAN_UK: "Результат",
            ARMENIAN_HY: "Արդյունք",
            HEBREW_HE: "תוצאה",
            ARABIC_AR: "النتيجة",
            THAI_TH: "ผลลัพธ์",
            LATIN_LA: "Resultatum",
            IRISH_GA: "Toradh",
            BELARUSIAN_BE: "Вынік",
            ODIA_OR: "ଫଳାଫଳ",
            FILIPINO_TL: "Resulta",
        }




        s.Exclude_Note = {
            ENGLISH_EN: "Exclude Note",
            JAPANESE_JA: "除外するノート",
            PORTUGUES_PT: "Excluir Nota",
            DEUTSCH_DE: "Notiz ausschließen",
            FRANCAIS_FR: "Exclure la note",
            PERSIAN_FA: "حذف یادداشت",
            RUSSIAN_RU: "Исключить заметку",
            ESPANOL_ES: "Excluir Nota",
            TIENG_VIET_VI: "Loại trừ Ghi chú",
            # ---------
            AFRIKAANS_AF: "Sluit Nota uit",
            BAHASA_MELAYU_MS: "Kecualikan Nota",
            CATALA_CA: "Exclou Nota",
            DANSK_DA: "Ekskluder Note",
            EESTI_ET: "Jäta märkus välja",
            ESPERANTO_EO: "Ekskluzivi Noto",
            EUSKARA_EU: "Ez inkluditu Oharra",
            GALEGO_GL: "Excluír Nota",
            HRVATSKI_HR: "Isključi Bilješku",
            ITALIANO_IT: "Escludi Nota",
            LO_JBOBAU_JBO: "Exclude Note",
            LENGA_DOC_OC: "Ekskluzi Notu",
            MAGYAR_HU: "Megjegyzés kizárása",
            NEDERLANDS_NL: "Notitie uitsluiten",
            NORSK_NB: "Ekskluder Notat",
            POLSKI_PL: "Wyklucz Notatkę",
            ROMANA_RO: "Excludeți Nota",
            SLOVENCINA_SK: "Vylúčiť Poznámku",
            SLOVENSCINA_SL: "Izključi Opombo",
            SUOMI_FI: "Poissulje Huomautus",
            SVENSKA_SV: "Exkludera Anteckning",
            TURKCE_TR: "Notu Hariç Tut",
            SIMPLIFIED_CHINESE_ZH: "排除笔记",
            KOREAN_KO: "노트 제외",
            CESTINA_CS: "Vyloučit Poznámku",
            HELLENIC_EL: "Αποκλείω Σημείωση",
            BULGARIAN_BG: "Изключи Бележка",
            MONGOL_MN: "Тэмдэглэл хасах",
            SERBIAN_SR: "Искључи Белешку",
            UKRAINIAN_UK: "Виключити Примітку",
            ARMENIAN_HY: "Բացակայել Նշումը",
            HEBREW_HE: "הוסף הערה",
            ARABIC_AR: "استبعاد الملاحظة",
            THAI_TH: "ยกเว้นบันทึก",
            LATIN_LA: "Exclude Note",
            IRISH_GA: "Sléacht Nota",
            BELARUSIAN_BE: "Выключыць Запіс",
            ODIA_OR: "ବିକଳ୍ପ କରନ୍ତୁ ନୋଟ",
            FILIPINO_TL: "I-exclude ang Talaan",
        }



        s.study_content_from_tags = {
            ENGLISH_EN: "study content from tags",
            JAPANESE_JA: "タグから勉強内容を取得",
            PORTUGUES_PT: "obter conteúdo de estudo a partir de tags",
            DEUTSCH_DE: "Studieninhalt aus Tags abrufen",
            FRANCAIS_FR: "obtenir le contenu d'étude à partir des balises",
            PERSIAN_FA: "دریافت محتوای مطالعه از برچسب‌ها",
            RUSSIAN_RU: "получить содержимое изучения из тегов",
            ESPANOL_ES: "obtener contenido de estudio de las etiquetas",
            TIENG_VIET_VI: "lấy nội dung học từ các thẻ",
            # ---------
            AFRIKAANS_AF: "kry inhoud van studie uit etikette",
            BAHASA_MELAYU_MS: "dapatkan kandungan pengajian dari tag",
            CATALA_CA: "obtenir contingut d'estudi des de les etiquetes",
            DANSK_DA: "få studieindhold fra tags",
            EESTI_ET: "saada õppesisu siltidest",
            ESPERANTO_EO: "akiri studokontenon el etikedoj",
            EUSKARA_EU: "etiketatik ikasgaiaren edukia lortu",
            GALEGO_GL: "obter contido de estudo das etiquetas",
            HRVATSKI_HR: "dobiti sadržaj za učenje iz oznaka",
            ITALIANO_IT: "ottenere il contenuto di studio dalle etichette",
            LO_JBOBAU_JBO: "klama lo stidi se pi'o le tegybau",
            LENGA_DOC_OC: "akiri studokontenon el etikedoj",
            MAGYAR_HU: "tanulmányi tartalom lekérése címkékből",
            NEDERLANDS_NL: "studie-inhoud ophalen uit tags",
            NORSK_NB: "få studieinnhold fra koder",
            POLSKI_PL: "uzyskaj treść nauki z tagów",
            ROMANA_RO: "obține conținutul de studiu din etichete",
            SLOVENCINA_SK: "získať obsah štúdia z tagov",
            SLOVENSCINA_SL: "pridobitev vsebine študija iz oznak",
            SUOMI_FI: "hanki opiskelusisältö tunnisteista",
            SVENSKA_SV: "få studieinnehåll från taggar",
            TURKCE_TR: "etiketlerden öğrenme içeriği al",
            SIMPLIFIED_CHINESE_ZH: "从标签中获取学习内容",
            KOREAN_KO: "태그에서 학습 콘텐츠 가져오기",
            CESTINA_CS: "získat obsah studia z tagů",
            HELLENIC_EL: "λήψη περιεχομένου μελέτης από ετικέτες",
            BULGARIAN_BG: "получаване на съдържание за учене от етикети",
            MONGOL_MN: "судалгааны агуулгыг тагуудаас авах",
            SERBIAN_SR: "добити садржај за учење из ознака",
            UKRAINIAN_UK: "отримати вміст навчання з тегів",
            ARMENIAN_HY: "սովորական բովանդակությունը ստանալ պիտակներից",
            HEBREW_HE: "קבל תוכן לימוד מתגים",
            ARABIC_AR: "الحصول على محتوى الدراسة من العلامات",
            THAI_TH: "รับเนื้อหาการศึกษาจากแท็ก",
            LATIN_LA: "obtinere continut de studiu din etichete",
            IRISH_GA: "faigh ábhar staidéir ó thagarthaí",
            BELARUSIAN_BE: "атрымаць змест навучання з тэгаў",
            ODIA_OR: "ଟ୍ୟାଗରୁ ଅଧ୍ୟଯନ ବିଷୟବସ୍ତୁ ପଡ଼ାନ୍ତୁ",
            FILIPINO_TL: "kuhanin ang nilalaman ng pag-aaral mula sa mga tatak",
        }



        s.Shortcut_Key = {
            ENGLISH_EN: "Shortcut_Key",
            JAPANESE_JA: "ショートカットキー",
            PORTUGUES_PT: "Chave de Atalho",
            DEUTSCH_DE: "Tastenkombination",
            FRANCAIS_FR: "Raccourci Clavier",
            PERSIAN_FA: "کلید میانبر",
            RUSSIAN_RU: "Горячая клавиша",
            ESPANOL_ES: "Tecla de Acceso Directo",
            TIENG_VIET_VI: "Phím Tắt",
            # ---------
            AFRIKAANS_AF: "Sleutelkombinasie",
            BAHASA_MELAYU_MS: "Kunci Pintas",
            CATALA_CA: "Drecera de Teclat",
            DANSK_DA: "Genvejstast",
            EESTI_ET: "Kiirklahv",
            ESPERANTO_EO: "Fulmoklavo",
            EUSKARA_EU: "Teklatu Azkarra",
            GALEGO_GL: "Tecla de Atallo",
            HRVATSKI_HR: "Prečac",
            ITALIANO_IT: "Tasto di Scelta Rapida",
            LO_JBOBAU_JBO: "Klani",
            LENGA_DOC_OC: "Klaviŝokombino",
            MAGYAR_HU: "Gyorsbillentyű",
            NEDERLANDS_NL: "Sneltoets",
            NORSK_NB: "Snarvei",
            POLSKI_PL: "Skrót Klawiszowy",
            ROMANA_RO: "Tastă de Scurtătură",
            SLOVENCINA_SK: "Skratka",
            SLOVENSCINA_SL: "Bližnjica",
            SUOMI_FI: "Pikanäppäin",
            SVENSKA_SV: "Genväg",
            TURKCE_TR: "Kısayol Tuşu",
            SIMPLIFIED_CHINESE_ZH: "快捷键",
            KOREAN_KO: "바로 가기 키",
            CESTINA_CS: "Klávesová zkratka",
            HELLENIC_EL: "Συντόμευση Πλήκτρου",
            BULGARIAN_BG: "Клавишна Комбинация",
            MONGOL_MN: "Товчлуур",
            SERBIAN_SR: "Пречица",
            UKRAINIAN_UK: "Гаряча Клавіша",
            ARMENIAN_HY: "Շորտկատարյան Ստեղնաշար",
            HEBREW_HE: "מקש קיצור",
            ARABIC_AR: "مفتاح اختصار",
            THAI_TH: "ปุ่มลัด",
            LATIN_LA: "Clavis Brevior",
            IRISH_GA: "Eochair giorraithe",
            BELARUSIAN_BE: "Гарачая клавіша",
            ODIA_OR: "ଶୋର୍ଟକଟ୍ କି",
            FILIPINO_TL: "Shortcut Key",
        }


        s.Auto_Prompt = {
            ENGLISH_EN: "Auto Prompt",
            JAPANESE_JA: "自動プロンプト",
            PORTUGUES_PT: "Prompt Automático",
            DEUTSCH_DE: "Automatische Eingabeaufforderung",
            FRANCAIS_FR: "Invite automatique",
            PERSIAN_FA: "پیشنهاد خودکار",
            RUSSIAN_RU: "Автоматическое предложение",
            ESPANOL_ES: "Sugerencia automática",
            TIENG_VIET_VI: "Gợi ý tự động",
            # ---------
            AFRIKAANS_AF: "Outomatiese Aanwysing",
            BAHASA_MELAYU_MS: "Petunjuk Auto",
            CATALA_CA: "Suggeriment Automàtic",
            DANSK_DA: "Automatisk Prompt",
            EESTI_ET: "Automaatne vihje",
            ESPERANTO_EO: "Aŭtomata Sugesto",
            EUSKARA_EU: "Berezko Oharra",
            GALEGO_GL: "Suxestión Automática",
            HRVATSKI_HR: "Automatski Podsticaj",
            ITALIANO_IT: "Suggerimento Automatico",
            LO_JBOBAU_JBO: "Klani Jikca",
            LENGA_DOC_OC: "Aŭtomata Sugesto",
            MAGYAR_HU: "Automatikus Prompt",
            NEDERLANDS_NL: "Automatische Prompt",
            NORSK_NB: "Automatisk Påminnelse",
            POLSKI_PL: "Automatyczne Podpowiedzi",
            ROMANA_RO: "Sugestie Automată",
            SLOVENCINA_SK: "Automatická Nápoveda",
            SLOVENSCINA_SL: "Samodejni Predlog",
            SUOMI_FI: "Automaattinen Ehdotus",
            SVENSKA_SV: "Automatiskt Förslag",
            TURKCE_TR: "Otomatik İpucu",
            SIMPLIFIED_CHINESE_ZH: "自动提示",
            KOREAN_KO: "자동 프롬프트",
            CESTINA_CS: "Automatický Návrh",
            HELLENIC_EL: "Αυτόματη Πρόταση",
            BULGARIAN_BG: "Автоматично Предложение",
            MONGOL_MN: "Автоматжуулсан Зөвлөгөө",
            SERBIAN_SR: "Аутоматска Понуда",
            UKRAINIAN_UK: "Автоматична Пропозиція",
            ARMENIAN_HY: "Ինքնաշխատ Խնդրում",
            HEBREW_HE: "הצעה אוטומטית",
            ARABIC_AR: "اقتراح تلقائي",
            THAI_TH: "คำแนะนำอัตโนมัติ",
            LATIN_LA: "Sugestio Automata",
            IRISH_GA: "Moltaí Uathoibríoch",
            BELARUSIAN_BE: "Аўтаматычнае Прапанова",
            ODIA_OR: "ଆପତକାଲିନ ପ୍ରମାଣିକ",
            FILIPINO_TL: "Auto Prompt",
        }

        s.Sidebar = {
            ENGLISH_EN: "Sidebar",
            JAPANESE_JA: "サイドバー",
            PORTUGUES_PT: "Barra lateral",
            DEUTSCH_DE: "Seitenleiste",
            FRANCAIS_FR: "Barre latérale",
            PERSIAN_FA: "نوار کناری",
            RUSSIAN_RU: "Боковая панель",
            ESPANOL_ES: "Barra lateral",
            TIENG_VIET_VI: "Thanh bên",
            # ---------
            AFRIKAANS_AF: "Sykant",
            BAHASA_MELAYU_MS: "Bar sisi",
            CATALA_CA: "Barra lateral",
            DANSK_DA: "Sidebjælke",
            EESTI_ET: "Külgriba",
            ESPERANTO_EO: "Flanka breto",
            EUSKARA_EU: "Alboko barraren",
            GALEGO_GL: "Barra lateral",
            HRVATSKI_HR: "Bočna traka",
            ITALIANO_IT: "Barra laterale",
            LO_JBOBAU_JBO: "Barja'o",
            LENGA_DOC_OC: "Flanka breto",
            MAGYAR_HU: "Oldalsáv",
            NEDERLANDS_NL: "Zijbalk",
            NORSK_NB: "Sidefelt",
            POLSKI_PL: "Pasek boczny",
            ROMANA_RO: "Bară laterală",
            SLOVENCINA_SK: "Bočný panel",
            SLOVENSCINA_SL: "Stranska vrstica",
            SUOMI_FI: "Sivupalkki",
            SVENSKA_SV: "Sidofält",
            TURKCE_TR: "Kenar çubuğu",
            SIMPLIFIED_CHINESE_ZH: "侧边栏",
            KOREAN_KO: "사이드바",
            CESTINA_CS: "Boční panel",
            HELLENIC_EL: "Πλευρική γραμμή",
            BULGARIAN_BG: "Странична лента",
            MONGOL_MN: "Хажуугийн самбар",
            SERBIAN_SR: "Бочна трака",
            UKRAINIAN_UK: "Бічна панель",
            ARMENIAN_HY: "Բուղարկան վահանակ",
            HEBREW_HE: "סרגל צד",
            ARABIC_AR: "الشريط الجانبي",
            THAI_TH: "แถบด้านข้าง",
            LATIN_LA: "Barra lateralis",
            IRISH_GA: "Barra taobh",
            BELARUSIAN_BE: "Бакавая панэль",
            ODIA_OR: "ପାଇଁ ବାର୍",
            FILIPINO_TL: "Sidebar",
        }



        s.Prompts = {
            ENGLISH_EN: "Prompts",
            JAPANESE_JA: "プロンプト",
            PORTUGUES_PT: "Prompts",
            DEUTSCH_DE: "Aufforderungen",
            FRANCAIS_FR: "Indications",
            PERSIAN_FA: "پیشنهادات",
            RUSSIAN_RU: "Подсказки",
            ESPANOL_ES: "Indicaciones",
            TIENG_VIET_VI: "Câu hỏi",
            # ---------
            AFRIKAANS_AF: "Vrae",
            BAHASA_MELAYU_MS: "Petunjuk",
            CATALA_CA: "Prompts",
            DANSK_DA: "Opgaver",
            EESTI_ET: "Küsimused",
            ESPERANTO_EO: "Demandoj",
            EUSKARA_EU: "Galderak",
            GALEGO_GL: "Prompts",
            HRVATSKI_HR: "Upiti",
            ITALIANO_IT: "Prompts",
            LO_JBOBAU_JBO: "Prompts",
            LENGA_DOC_OC: "Demandoj",
            MAGYAR_HU: "Feladatok",
            NEDERLANDS_NL: "Vragen",
            NORSK_NB: "Spørsmål",
            POLSKI_PL: "Podpowiedzi",
            ROMANA_RO: "Prompts",
            SLOVENCINA_SK: "Otázky",
            SLOVENSCINA_SL: "Vprašanja",
            SUOMI_FI: "Kysymykset",
            SVENSKA_SV: "Frågor",
            TURKCE_TR: "İpuçları",
            SIMPLIFIED_CHINESE_ZH: "提示",
            KOREAN_KO: "프롬프트",
            CESTINA_CS: "Otázky",
            HELLENIC_EL: "Ερωτήσεις",
            BULGARIAN_BG: "Въпроси",
            MONGOL_MN: "Асуултууд",
            SERBIAN_SR: "Питања",
            UKRAINIAN_UK: "Питання",
            ARMENIAN_HY: "Հարցեր",
            HEBREW_HE: "שאלות",
            ARABIC_AR: "أسئلة",
            THAI_TH: "คำถาม",
            LATIN_LA: "Quaestiones",
            IRISH_GA: "Ceisteanna",
            BELARUSIAN_BE: "Пытанні",
            ODIA_OR: "ପ୍ରଶ୍ନଗୁଡ଼ିକ",
            FILIPINO_TL: "Mga Tanong",
        }

        s.auto_hide_sidebar_on_review_questions = {
            ENGLISH_EN: "auto hide sidebar on review questions",
            JAPANESE_JA: "回答を表示したらサイドバーを自動で隠す",
            PORTUGUES_PT: "ocultar automaticamente a barra lateral nas perguntas de revisão",
            DEUTSCH_DE: "Seitenleiste bei Überprüfungsfragen automatisch ausblenden",
            FRANCAIS_FR: "masquer automatiquement la barre latérale lors des questions de révision",
            PERSIAN_FA: "مخفی کردن خودکار نوار کناری در سوالات مرور",
            RUSSIAN_RU: "автоматически скрывать боковую панель при проверке вопросов",
            ESPANOL_ES: "ocultar automáticamente la barra lateral en las preguntas de revisión",
            TIENG_VIET_VI: "tự động ẩn thanh bên khi xem câu hỏi đánh giá",
            # ---------
            AFRIKAANS_AF: "outomatiese versteek van sybalk met hersieningsvrae",
            BAHASA_MELAYU_MS: "sembunyikan sidebar secara automatik pada soalan semakan",
            CATALA_CA: "amaga automàticament la barra lateral a les preguntes de revisió",
            DANSK_DA: "automatisk skjul sidepanelet på gennemgangsspørgsmål",
            EESTI_ET: "peida külgriba automaatselt ülevaatamisküsimustes",
            ESPERANTO_EO: "aŭtomate kaŝi flankan breton pri reviziesdemandoj",
            EUSKARA_EU: "ezkutatu alboko barraren automatikoki berrikuspen galderetan",
            GALEGO_GL: "ocultar automaticamente a barra lateral nas preguntas de revisión",
            HRVATSKI_HR: "automatsko skrivanje bočne trake na pitanjima za pregled",
            ITALIANO_IT: "nascondi automaticamente la barra laterale nelle domande di revisione",
            LO_JBOBAU_JBO: "banzu sepli lo sefta lo se spaji",
            LENGA_DOC_OC: "automate skriti stransko vrstico pri preglednih vprašanjih",
            MAGYAR_HU: "automatikus oldalsáv elrejtése a felülvizsgálati kérdéseknél",
            NEDERLANDS_NL: "automatisch zijbalk verbergen bij beoordelingsvragen",
            NORSK_NB: "automatisk skjul sidepanelet på gjennomgangsspørsmål",
            POLSKI_PL: "automatyczne ukrywanie paska bocznego w pytaniach do powtórki",
            ROMANA_RO: "ascunde automat bara laterală la întrebările de revizuire",
            SLOVENCINA_SK: "automaticky skryť bočný panel pri otázkach na opakovanie",
            SLOVENSCINA_SL: "samodejno skrij stransko vrstico pri vprašanjih za pregled",
            SUOMI_FI: "piilota sivupalkki automaattisesti kertauskysymyksissä",
            SVENSKA_SV: "automatiskt dölj sidofältet vid översiktsfrågor",
            TURKCE_TR: "inceleme sorularında kenar çubuğunu otomatik olarak gizle",
            SIMPLIFIED_CHINESE_ZH: "在复习问题上自动隐藏侧边栏",
            KOREAN_KO: "복습 질문에서 사이드바 자동 숨기기",
            CESTINA_CS: "automaticky skrýt boční panel u přezkumných otázek",
            HELLENIC_EL: "αυτόματη απόκρυψη πλευρικής γραμμής στις ερωτήσεις αναθεώρησης",
            BULGARIAN_BG: "автоматично скриване на страничната лента при прегледни въпроси",
            MONGOL_MN: "шалгалтын асуултуудад хажуугийн самбарыг автоматаар нуух",
            SERBIAN_SR: "automatsko sakrivanje bočne trake na pitanjima za pregled",
            UKRAINIAN_UK: "автоматично приховувати бічну панель на питаннях для перегляду",
            ARMENIAN_HY: "ավտոմատ թաքցնել կողմնակի վահանակը վերանայման հարցերում",
            HEBREW_HE: "הסתר אוטומטי של סרגל הצד בשאלות בסיקור",
            ARABIC_AR: "إخفاء الشريط الجانبي تلقائيًا في أسئلة المراجعة",
            THAI_TH: "ซ่อนแถบด้านข้างโดยอัตโนมัติในคำถามการทบทวน",
            LATIN_LA: "automate occultare columnam lateralem in quaestionibus recensendis",
            IRISH_GA: "folúntas ghabhála taobhghlasa ar cheisteanna athbhreithnithe",
            BELARUSIAN_BE: "аўтаматычна схаваць бакавую панэль на пытаннях для перагляду",
            ODIA_OR: "ପ୍ରଶ୍ନଗୁଡ଼ିକରେ ସ୍ବୟଂକ୍ରିୟ ଭାବରେ ସାଇଡବାର୍ ଲୁଚାନ୍ତୁ",
            FILIPINO_TL: "awtomatikong itago ang sidebar sa mga tanong sa pagsusuri",
        }


        s.auto_send_prompts = {
            ENGLISH_EN: "auto send prompts",
            JAPANESE_JA: "プロンプトを自動送信",
            PORTUGUES_PT: "enviar prompts automaticamente",
            DEUTSCH_DE: "automatisch Prompts senden",
            FRANCAIS_FR: "envoyer automatiquement des invites",
            PERSIAN_FA: "ارسال خودکار Prompts",
            RUSSIAN_RU: "автоматическая отправка подсказок",
            ESPANOL_ES: "enviar automáticamente las indicaciones",
            TIENG_VIET_VI: "tự động gửi lời nhắc",
            # ---------
            AFRIKAANS_AF: "outomatiese stuur van aansporings",
            BAHASA_MELAYU_MS: "hantar prompts secara automatik",
            CATALA_CA: "enviar automàticament les indicacions",
            DANSK_DA: "send prompts automatisk",
            EESTI_ET: "saada automaatselt vihjeid",
            ESPERANTO_EO: "sendi aŭtomate proponojn",
            EUSKARA_EU: "bidali automatikoki gomendioak",
            GALEGO_GL: "enviar automaticamente as indicacións",
            HRVATSKI_HR: "automatsko slanje uputa",
            ITALIANO_IT: "inviare automaticamente le indicazioni",
            LO_JBOBAU_JBO: "xaksu sepli lo sefta",
            LENGA_DOC_OC: "sendi aŭtomate sugestojn",
            MAGYAR_HU: "automatikus üzenetküldés",
            NEDERLANDS_NL: "automatisch prompts verzenden",
            NORSK_NB: "sende prompts automatisk",
            POLSKI_PL: "automatyczne wysyłanie podpowiedzi",
            ROMANA_RO: "trimite automat prompt-uri",
            SLOVENCINA_SK: "automaticky odoslať podnety",
            SLOVENSCINA_SL: "avtomatsko pošiljanje spodbud",
            SUOMI_FI: "lähetä automaattisesti vihjeitä",
            SVENSKA_SV: "skicka automatiska påminnelser",
            TURKCE_TR: "otomatik olarak ipuçları gönder",
            SIMPLIFIED_CHINESE_ZH: "自动发送提示",
            KOREAN_KO: "자동으로 프롬프트 보내기",
            CESTINA_CS: "automaticky odeslat podněty",
            HELLENIC_EL: "αυτόματη αποστολή υποδείξεων",
            BULGARIAN_BG: "автоматично изпращане на подсказки",
            MONGOL_MN: "автоматаар илгээх заавар",
            SERBIAN_SR: "automatsko slanje podsticaja",
            UKRAINIAN_UK: "автоматичне надсилання підказок",
            ARMENIAN_HY: "ավտոմատ ուղարկել հուշեր",
            HEBREW_HE: "שליחת פרומפטים אוטומטית",
            ARABIC_AR: "إرسال الدلائل تلقائيًا",
            THAI_TH: "ส่งข้อความเตือนโดยอัตโนมัติ",
            LATIN_LA: "automate mittere monita",
            IRISH_GA: "cuir glaoch ar phrompts go huathoibríoch",
            BELARUSIAN_BE: "аўтаматычная дасылка падказак",
            ODIA_OR: "ସ୍ବୟଂକ୍ରିୟ ପ୍ରେରଣାଦେଶ ପଠାନ୍ତୁ",
            FILIPINO_TL: "awtomatikong magpadala ng mga prompt",
        }




        s.auto_input_prompts = {
            ENGLISH_EN: "auto input prompts",
            JAPANESE_JA: "プロンプトを自動入力",
            PORTUGUES_PT: "preenchimento automático de prompts",
            DEUTSCH_DE: "automatische Eingabe von Prompts",
            FRANCAIS_FR: "saisie automatique des invites",
            PERSIAN_FA: "ورود خودکار Prompts",
            RUSSIAN_RU: "автоматический ввод подсказок",
            ESPANOL_ES: "entrada automática de indicaciones",
            TIENG_VIET_VI: "tự động nhập lời nhắc",
            # ---------
            AFRIKAANS_AF: "outomatiese intik van aansporings",
            BAHASA_MELAYU_MS: "input automatik prompts",
            CATALA_CA: "entrada automàtica de les indicacions",
            DANSK_DA: "automatisk indtastning af prompts",
            EESTI_ET: "automaatne sisestamine",
            ESPERANTO_EO: "aŭtomata enigo de proponoj",
            EUSKARA_EU: "automatikoki sarrera gomendioak",
            GALEGO_GL: "entrada automática das indicacións",
            HRVATSKI_HR: "automatski unos uputa",
            ITALIANO_IT: "inserimento automatico degli indirizzi",
            LO_JBOBAU_JBO: "zmadu lo sepli lo sefta",
            LENGA_DOC_OC: "aŭtomata enigo de sugestoj",
            MAGYAR_HU: "automatikus bevitel",
            NEDERLANDS_NL: "automatische invoer van prompts",
            NORSK_NB: "automatisk inntasting av påminnelser",
            POLSKI_PL: "automatyczne wprowadzanie podpowiedzi",
            ROMANA_RO: "introducere automată a prompturilor",
            SLOVENCINA_SK: "automatické zadávanie podnetov",
            SLOVENSCINA_SL: "avtomatsko vnašanje spodbud",
            SUOMI_FI: "automaattinen syöttö",
            SVENSKA_SV: "automatisk inmatning av påminnelser",
            TURKCE_TR: "otomatik giriş ipuçları",
            SIMPLIFIED_CHINESE_ZH: "自动输入提示",
            KOREAN_KO: "자동으로 프롬프트 입력",
            CESTINA_CS: "automatické zadávání podnětů",
            HELLENIC_EL: "αυτόματη εισαγωγή υποδείξεων",
            BULGARIAN_BG: "автоматично въвеждане на подсказки",
            MONGOL_MN: "автоматаар оруулах заавар",
            SERBIAN_SR: "automatsko unošenje podsticaja",
            UKRAINIAN_UK: "автоматичне введення підказок",
            ARMENIAN_HY: "ավտոմատ մուտքագրել հուշեր",
            HEBREW_HE: "הזנת פרומפטים אוטומטית",
            ARABIC_AR: "إدخال الدلائل تلقائيًا",
            THAI_TH: "ป้อนข้อความเตือนโดยอัตโนมัติ",
            LATIN_LA: "automate input monita",
            IRISH_GA: "ionchur uathoibríoch a chur ar phrompts",
            BELARUSIAN_BE: "аўтаматычны ўвод падказак",
            ODIA_OR: "ସ୍ବୟଂକ୍ରିୟ ଇନପୁଟ ପଠାନ୍ତୁ",
            FILIPINO_TL: "awtomatikong input ng mga prompt",
        }



        s.add_ai_icon_button_to_the_top_toolbar = {
            ENGLISH_EN: "add Ai icon button to the top toolbar",
            JAPANESE_JA: "AIアイコンをトップツールバーに追加する",
            PORTUGUES_PT: "adicionar botão de ícone de IA à barra de ferramentas superior",
            DEUTSCH_DE: "KI-Symbol zur Symbolleiste hinzufügen",
            FRANCAIS_FR: "ajouter un bouton d'icône IA à la barre d'outils supérieure",
            PERSIAN_FA: "افزودن دکمه آیکون هوش مصنوعی به نوار ابزار بالا",
            RUSSIAN_RU: "добавить кнопку иконки ИИ в верхнюю панель инструментов",
            ESPANOL_ES: "agregar el botón de icono de IA a la barra de herramientas superior",
            TIENG_VIET_VI: "thêm nút biểu tượng AI vào thanh công cụ trên cùng",
            # ---------
            AFRIKAANS_AF: "voeg 'n KI-ikoonknoppie by die boonste nutsbalk by",
            BAHASA_MELAYU_MS: "tambah butang ikon AI ke toolbar atas",
            CATALA_CA: "afegir el botó d'icona d'IA a la barra d'eines superior",
            DANSK_DA: "tilføj AI-ikonknappen til den øverste værktøjslinje",
            EESTI_ET: "lisage AI-iikoon nuppu ülemisele tööriistaribale",
            ESPERANTO_EO: "aldoni AI-ikonan butonon al la supra ilobreto",
            EUSKARA_EU: "gehi AI ikono botoia goiko tresnabarran",
            GALEGO_GL: "engadir o botón de icona de IA á barra de ferramentas superior",
            HRVATSKI_HR: "dodajte gumb ikone AI na gornju traku s alatima",
            ITALIANO_IT: "aggiungi il pulsante dell'icona IA alla barra degli strumenti superiore",
            LO_JBOBAU_JBO: "zmadu lo sepli lo sefta lo sefta",
            LENGA_DOC_OC: "aldoni AI-ikonan butonon al la supre ilobreto",
            MAGYAR_HU: "AI ikon gomb hozzáadása a felső eszköztárhoz",
            NEDERLANDS_NL: "voeg een AI-pictogramknop toe aan de bovenste werkbalk",
            NORSK_NB: "legg til AI-ikonknappen i toppverktøylinjen",
            POLSKI_PL: "dodaj przycisk ikony AI do górnego paska narzędzi",
            ROMANA_RO: "adăugați butonul de pictogramă AI în bara de instrumente superioară",
            SLOVENCINA_SK: "pridať tlačidlo ikony AI na hornú panel nástrojov",
            SLOVENSCINA_SL: "dodaj ikono AI na vrhnjo orodno vrstico",
            SUOMI_FI: "lisää AI-kuvakkeen painike ylätyökaluriville",
            SVENSKA_SV: "lägg till AI-ikonen i den övre verktygsraden",
            TURKCE_TR: "üst araç çubuğuna AI simge düğmesi ekle",
            SIMPLIFIED_CHINESE_ZH: "将AI图标按钮添加到顶部工具栏",
            KOREAN_KO: "AI 아이콘 버튼을 상단 도구 모음에 추가",
            CESTINA_CS: "přidat tlačítko ikony AI na horní panel nástrojů",
            HELLENIC_EL: "προσθέστε το κουμπί εικονιδίου AI στην επάνω γραμμή εργαλείων",
            BULGARIAN_BG: "добавете бутона на иконата на ИИ в горната лента с инструменти",
            MONGOL_MN: "AI дүрсийн товчийг дээд товчны самбар руу нэмэх",
            SERBIAN_SR: "dodajte dugme ikone veštačke inteligencije na gornju traku sa alatkama",
            UKRAINIAN_UK: "додайте кнопку іконки ШІ на верхню панель інструментів",
            ARMENIAN_HY: "ավելացրեք AI պատկերասրահի կոճակը վերնագրի վրա",
            HEBREW_HE: "הוסף כפתור סמל AI לסרגל הכלים העליון",
            ARABIC_AR: "إضافة زر رمز الذكاء الاصطناعي إلى شريط الأدوات العلوي",
            THAI_TH: "เพิ่มปุ่มไอคอน AI เข้าสู่แถบเครื่องมือด้านบน",
            LATIN_LA: "addere AI icon pulsante ad superius toolbar",
            IRISH_GA: "cuir cnaipe íomhá AI leis an gceartlár barr uachtair",
            BELARUSIAN_BE: "дадаць кнопку значка штучнай інтэлекту на верхнюю панэль інструментаў",
            ODIA_OR: "ଶିକ୍ଷାମୂଳକ ଆଇକନ୍ ବଟନ୍ ଟପ ଟୁଲବାରରେ ଯୋଡ଼ନ୍ତୁ",
            FILIPINO_TL: "magdagdag ng Ai icon button sa tuktok na toolbar",
        }


        s.auto_open_sidebar_when_start_anki = {
            ENGLISH_EN: "Auto open sidebar when start Anki",
            JAPANESE_JA: "Ankiを開いたらサイドバーを自動で開く",
            PORTUGUES_PT: "Abrir a barra lateral automaticamente ao iniciar o Anki",
            DEUTSCH_DE: "Seitenleiste automatisch öffnen beim Start von Anki",
            FRANCAIS_FR: "Ouvrir automatiquement la barre latérale au démarrage d'Anki",
            PERSIAN_FA: "باز کردن خودکار نوار کناری هنگام شروع Anki",
            RUSSIAN_RU: "Автоматическое открытие боковой панели при запуске Anki",
            ESPANOL_ES: "Abrir automáticamente la barra lateral al iniciar Anki",
            TIENG_VIET_VI: "Tự động mở thanh bên khi bắt đầu Anki",
            # ---------
            AFRIKAANS_AF: "Maak die sybalk oop wanneer Anki begin",
            BAHASA_MELAYU_MS: "Buka sidebar secara automatik apabila memulakan Anki",
            CATALA_CA: "Obriu la barra lateral automàticament en iniciar Anki",
            DANSK_DA: "Automatisk åbn sidepanelet, når Anki starter",
            EESTI_ET: "Avage külgriba automaatselt Anki käivitamisel",
            ESPERANTO_EO: "Aŭtomate malfermu la flankan breton kiam vi komencas Anki",
            EUSKARA_EU: "Barralde alboan ireki automatikoki Anki hasi denean",
            GALEGO_GL: "Abrir a barra lateral automaticamente ao iniciar Anki",
            HRVATSKI_HR: "Automatski otvorite bočnu traku pri pokretanju Anki",
            ITALIANO_IT: "Apri automaticamente la barra laterale all'avvio di Anki",
            LO_JBOBAU_JBO: "facki lo sepli lo sefta lo sefta",
            LENGA_DOC_OC: "Aŭtomate malfermu la flankan breton kiam vi komencas Anki",
            MAGYAR_HU: "Automatikusan nyissa meg az oldalsávot az Anki indításakor",
            NEDERLANDS_NL: "Automatisch de zijbalk openen bij het starten van Anki",
            NORSK_NB: "Åpne sidepanelet automatisk når Anki starter",
            POLSKI_PL: "Automatyczne otwieranie paska bocznego podczas uruchamiania Anki",
            ROMANA_RO: "Deschide automat bara laterală la pornirea Anki",
            SLOVENCINA_SK: "Automaticky otvorte bočný panel pri spustení Anki",
            SLOVENSCINA_SL: "Samodejno odprite stransko vrstico ob zagonu Anki",
            SUOMI_FI: "Avaa sivupalkki automaattisesti Anki:n käynnistyessä",
            SVENSKA_SV: "Öppna sidofältet automatiskt när Anki startar",
            TURKCE_TR: "Anki başladığında yan paneli otomatik olarak aç",
            SIMPLIFIED_CHINESE_ZH: "启动 Anki 时自动打开侧边栏",
            KOREAN_KO: "Anki 시작 시 사이드바 자동 열기",
            CESTINA_CS: "Automaticky otevřete postranní panel při spuštění Anki",
            HELLENIC_EL: "Αυτόματο άνοιγμα πλευρικής γραμμής κατά την έναρξη του Anki",
            BULGARIAN_BG: "Автоматично отваряне на страничната лента при стартиране на Anki",
            MONGOL_MN: "Anki эхлэхэд өөрчлөлтийн самбарыг автоматаар нээх",
            SERBIAN_SR: "Automatsko otvaranje bočne trake pri pokretanju Anki",
            UKRAINIAN_UK: "Автоматичне відкриття бічної панелі при запуску Anki",
            ARMENIAN_HY: "Ավտոմատ բացել կողմնակի վահանակը Anki-ի սկսելուն",
            HEBREW_HE: "פתיחה אוטומטית של סרגל הצד בהפעלת Anki",
            ARABIC_AR: "فتح الشريط الجانبي تلقائيًا عند بدء Anki",
            THAI_TH: "เปิดแถบด้านข้างโดยอัตโนมัติเมื่อเริ่ม Anki",
            LATIN_LA: "Automate aperi sidebar cum Anki incipit",
            IRISH_GA: "Oscail an taobhghléas go huathoibríoch nuair a thosaíonn tú Anki",
            BELARUSIAN_BE: "Аўтаматычна адчыніць бакавую панэль пры запуску Anki",
            ODIA_OR: "Anki ଆରମ୍ଭ ହେଲାରେ ସାଇଡବାରଟି ଆପମୁକ୍ତ କରନ୍ତୁ",
            FILIPINO_TL: "Buksan nang awtomatiko ang sidebar kapag nagsisimula ang Anki",
        }



        s.Use_Translate = {
            ENGLISH_EN: "Use Translate",
            JAPANESE_JA: "翻訳を使う",
            PORTUGUES_PT: "Usar Tradução",
            DEUTSCH_DE: "Übersetzung verwenden",
            FRANCAIS_FR: "Utiliser la traduction",
            PERSIAN_FA: "استفاده از ترجمه",
            RUSSIAN_RU: "Использовать перевод",
            ESPANOL_ES: "Usar Traducción",
            TIENG_VIET_VI: "Sử dụng Dịch",
            # ---------
            AFRIKAANS_AF: "Gebruik Vertaling",
            BAHASA_MELAYU_MS: "Gunakan Terjemahan",
            CATALA_CA: "Utilitza la traducció",
            DANSK_DA: "Brug oversættelse",
            EESTI_ET: "Kasuta tõlget",
            ESPERANTO_EO: "Uzi Tradukon",
            EUSKARA_EU: "Itzuli erabili",
            GALEGO_GL: "Usar Tradución",
            HRVATSKI_HR: "Koristite prijevod",
            ITALIANO_IT: "Usa Traduzione",
            LO_JBOBAU_JBO: "xamgu valsi",
            LENGA_DOC_OC: "Uzi Tradukon",
            MAGYAR_HU: "Fordítás használata",
            NEDERLANDS_NL: "Gebruik Vertaling",
            NORSK_NB: "Bruk Oversettelse",
            POLSKI_PL: "Użyj Tłumaczenia",
            ROMANA_RO: "Utilizați Traducerea",
            SLOVENCINA_SK: "Použite preklad",
            SLOVENSCINA_SL: "Uporabite prevod",
            SUOMI_FI: "Käytä käännöstä",
            SVENSKA_SV: "Använd Översättning",
            TURKCE_TR: "Çeviri Kullan",
            SIMPLIFIED_CHINESE_ZH: "使用翻译",
            KOREAN_KO: "번역 사용",
            CESTINA_CS: "Použít Překlad",
            HELLENIC_EL: "Χρησιμοποιήστε Μετάφραση",
            BULGARIAN_BG: "Използвайте Превод",
            MONGOL_MN: "Орчуулга Ашиглах",
            SERBIAN_SR: "Koristite prevod",
            UKRAINIAN_UK: "Використовуйте переклад",
            ARMENIAN_HY: "Օգտագործեք Թարգմանությունը",
            HEBREW_HE: "השתמש בתרגום",
            ARABIC_AR: "استخدم الترجمة",
            THAI_TH: "ใช้การแปล",
            LATIN_LA: "Usa Translationem",
            IRISH_GA: "Úsáid Aistriúcháin",
            BELARUSIAN_BE: "Выкарыстоўвайце Пераклад",
            ODIA_OR: "ଅନୁବାଦ ବ୍ୟବହାର କରନ୍ତୁ",
            FILIPINO_TL: "Gamitin ang Pagsasalin",
        }

        s.Use_Prefix = {
            ENGLISH_EN: "Use Prefix",
            JAPANESE_JA: "接頭辞を使う",
            PORTUGUES_PT: "Usar Prefixo",
            DEUTSCH_DE: "Präfix verwenden",
            FRANCAIS_FR: "Utiliser un préfixe",
            PERSIAN_FA: "استفاده از پیشوند",
            RUSSIAN_RU: "Использовать префикс",
            ESPANOL_ES: "Usar Prefijo",
            TIENG_VIET_VI: "Sử dụng Tiền tố",
            # ---------
            AFRIKAANS_AF: "Gebruik Voorvoegsel",
            BAHASA_MELAYU_MS: "Gunakan Awalan",
            CATALA_CA: "Utilitza el Prefix",
            DANSK_DA: "Brug Præfiks",
            EESTI_ET: "Kasuta Eesliidet",
            ESPERANTO_EO: "Uzi Prefikson",
            EUSKARA_EU: "Erabili Aurreko",
            GALEGO_GL: "Usar Prefixo",
            HRVATSKI_HR: "Koristite Prefiks",
            ITALIANO_IT: "Usa Prefisso",
            LO_JBOBAU_JBO: "xamgu valsi",
            LENGA_DOC_OC: "Uzi Prefikson",
            MAGYAR_HU: "Használjon Előtagot",
            NEDERLANDS_NL: "Gebruik Voorvoegsel",
            NORSK_NB: "Bruk Prefiks",
            POLSKI_PL: "Użyj Prefiksu",
            ROMANA_RO: "Utilizați Prefixul",
            SLOVENCINA_SK: "Použite Predponu",
            SLOVENSCINA_SL: "Uporabite Predpono",
            SUOMI_FI: "Käytä Etuliitettä",
            SVENSKA_SV: "Använd Prefix",
            TURKCE_TR: "Önek Kullan",
            SIMPLIFIED_CHINESE_ZH: "使用前缀",
            KOREAN_KO: "접두사 사용",
            CESTINA_CS: "Použít Předponu",
            HELLENIC_EL: "Χρησιμοποιήστε Πρόθεμα",
            BULGARIAN_BG: "Използвайте Приставка",
            MONGOL_MN: "Толгойг Ашиглах",
            SERBIAN_SR: "Koristite Prefiks",
            UKRAINIAN_UK: "Використовуйте Префікс",
            ARMENIAN_HY: "Օգտագործեք Նախագծին",
            HEBREW_HE: "השתמש בקידומת",
            ARABIC_AR: "استخدم البادئة",
            THAI_TH: "ใช้คำนำหน้า",
            LATIN_LA: "Usa Praefixum",
            IRISH_GA: "Úsáid Réamhfhocal",
            BELARUSIAN_BE: "Выкарыстоўвайце Прыставку",
            ODIA_OR: "ପ୍ରଥମରେ ଉପଯୋଗ କରନ୍ତୁ",
            FILIPINO_TL: "Gamitin ang Unlapi",
        }



        s.Priority_Fields = {
            ENGLISH_EN: "Priority Fields",
            JAPANESE_JA: "優先フィールド",
            PORTUGUES_PT: "Campos Prioritários",
            DEUTSCH_DE: "Prioritätsfelder",
            FRANCAIS_FR: "Champs de priorité",
            PERSIAN_FA: "فیلدهای اولویت",
            RUSSIAN_RU: "Приоритетные поля",
            ESPANOL_ES: "Campos de Prioridad",
            TIENG_VIET_VI: "Trường Ưu tiên",
            # ---------
            AFRIKAANS_AF: "Prioriteit Velde",
            BAHASA_MELAYU_MS: "Bidang Keutamaan",
            CATALA_CA: "Camps de prioritat",
            DANSK_DA: "Prioritetsfelter",
            EESTI_ET: "Eelistatud väljad",
            ESPERANTO_EO: "Prioritataj Kampo",
            EUSKARA_EU: "Lehentasuneko Eremuak",
            GALEGO_GL: "Campos de Prioridade",
            HRVATSKI_HR: "Prioritetna Polja",
            ITALIANO_IT: "Campi di Priorità",
            LO_JBOBAU_JBO: "rinka valsi",
            LENGA_DOC_OC: "Campi de Prioritat",
            MAGYAR_HU: "Prioritás Mezők",
            NEDERLANDS_NL: "Prioriteit Velden",
            NORSK_NB: "Prioritetsfelt",
            POLSKI_PL: "Pola Priorytetowe",
            ROMANA_RO: "Câmpuri Prioritare",
            SLOVENCINA_SK: "Prioritné Polia",
            SLOVENSCINA_SL: "Prednostna Polja",
            SUOMI_FI: "Tärkeyskentät",
            SVENSKA_SV: "Prioriterade Fält",
            TURKCE_TR: "Öncelikli Alanlar",
            SIMPLIFIED_CHINESE_ZH: "优先字段",
            KOREAN_KO: "우선 필드",
            CESTINA_CS: "Přednostní Pole",
            HELLENIC_EL: "Προτεραιότητα Πεδίων",
            BULGARIAN_BG: "Приоритетни Полета",
            MONGOL_MN: "Эрэмбэлэх Талбарууд",
            SERBIAN_SR: "Prioritetna Polja",
            UKRAINIAN_UK: "Пріоритетні Поля",
            ARMENIAN_HY: "Նախագծի Դաշտեր",
            HEBREW_HE: "שדות עדיפות",
            ARABIC_AR: "حقول الأولوية",
            THAI_TH: "ฟิลด์ลำดับความสำคัญ",
            LATIN_LA: "Campos Prioritatis",
            IRISH_GA: "Réimseanna Tosaíochta",
            BELARUSIAN_BE: "Прыярытэтныя Полі",
            ODIA_OR: "ପ୍ରାୟରେଟୀ କ୍ଷେତ୍ରଗୁଡ଼ିକ",
            FILIPINO_TL: "Mga Pangunahing Larangan",
        }




        s.Tags = {
            ENGLISH_EN: "Tags",
            JAPANESE_JA: "タグ",
            PORTUGUES_PT: "Tags",
            DEUTSCH_DE: "Tags",
            FRANCAIS_FR: "Tags",
            PERSIAN_FA: "برچسب‌ها",
            RUSSIAN_RU: "Теги",
            ESPANOL_ES: "Etiquetas",
            TIENG_VIET_VI: "Thẻ",
            # ---------
            AFRIKAANS_AF: "Tags",
            BAHASA_MELAYU_MS: "Tags",
            CATALA_CA: "Etiquetes",
            DANSK_DA: "Tags",
            EESTI_ET: "Sildid",
            ESPERANTO_EO: "Etikedoj",
            EUSKARA_EU: "Etiketak",
            GALEGO_GL: "Etiquetas",
            HRVATSKI_HR: "Oznake",
            ITALIANO_IT: "Tag",
            LO_JBOBAU_JBO: "Tags",
            LENGA_DOC_OC: "Etiquetas",
            MAGYAR_HU: "Címkék",
            NEDERLANDS_NL: "Tags",
            NORSK_NB: "Tags",
            POLSKI_PL: "Tagi",
            ROMANA_RO: "Etichete",
            SLOVENCINA_SK: "Tagy",
            SLOVENSCINA_SL: "Oznake",
            SUOMI_FI: "Tunnisteet",
            SVENSKA_SV: "Taggar",
            TURKCE_TR: "Etiketler",
            SIMPLIFIED_CHINESE_ZH: "标签",
            KOREAN_KO: "태그",
            CESTINA_CS: "Štítky",
            HELLENIC_EL: "Ετικέτες",
            BULGARIAN_BG: "Етикети",
            MONGOL_MN: "Таг",
            SERBIAN_SR: "Oznake",
            UKRAINIAN_UK: "Теги",
            ARMENIAN_HY: "Պիտակներ",
            HEBREW_HE: "תגיות",
            ARABIC_AR: "العلامات",
            THAI_TH: "แท็ก",
            LATIN_LA: "Tags",
            IRISH_GA: "Clibeanna",
            BELARUSIAN_BE: "Тэгі",
            ODIA_OR: "ଟ୍ୟାଗ୍‌ଗୁଡ଼ିକ",
            FILIPINO_TL: "Mga Tag",
        }


        s.Open_Sidebar = {
            ENGLISH_EN : "Open Sidebar",
            JAPANESE_JA : "サイドバーを開く",
            PORTUGUES_PT : "Abrir Barra Lateral",
            DEUTSCH_DE : "Seitenleiste öffnen",
            FRANCAIS_FR : "Ouvrir la barre latérale",
            PERSIAN_FA : "باز کردن نوار کناری",
            RUSSIAN_RU : "Открыть боковую панель",
            ESPANOL_ES : "Abrir barra lateral",
            TIENG_VIET_VI : "Mở thanh bên",
            # ---------
            AFRIKAANS_AF : "Open Sybalk",
            BAHASA_MELAYU_MS : "Buka Sidebar",
            CATALA_CA : "Obre la barra lateral",
            DANSK_DA : "Åbn sidepanelet",
            EESTI_ET : "Ava küljepaan",
            ESPERANTO_EO : "Malfermu flankan breton",
            EUSKARA_EU : "Ireki alboko barraren",
            GALEGO_GL : "Abrir a barra lateral",
            HRVATSKI_HR : "Otvori bočnu traku",
            ITALIANO_IT : "Apri la barra laterale",
            LO_JBOBAU_JBO : "Open Sidebar",
            LENGA_DOC_OC : "Obrir la barra lateral",
            MAGYAR_HU : "Oldalsáv megnyitása",
            NEDERLANDS_NL : "Zijbalk openen",
            NORSK_NB : "Åpne sidepanelet",
            POLSKI_PL : "Otwórz pasek boczny",
            ROMANA_RO : "Deschide bara laterală",
            SLOVENCINA_SK : "Otvoriť bočný panel",
            SLOVENSCINA_SL : "Odpri stransko vrstico",
            SUOMI_FI : "Avaa sivupalkki",
            SVENSKA_SV : "Öppna sidopanelen",
            TURKCE_TR : "Kenar Çubuğunu Aç",
            SIMPLIFIED_CHINESE_ZH : "打开侧边栏",
            KOREAN_KO : "사이드바 열기",
            CESTINA_CS : "Otevřít postranní panel",
            HELLENIC_EL : "Άνοιγμα πλευρικής γραμμής",
            BULGARIAN_BG : "Отвори страничната лента",
            MONGOL_MN : "Хажуугаар нээх",
            SERBIAN_SR : "Otvori bočnu traku",
            UKRAINIAN_UK : "Відкрити бічну панель",
            ARMENIAN_HY : "Բացել կողմնակերպությունը",
            HEBREW_HE : "פתח את סרגל הצד",
            ARABIC_AR : "فتح الشريط الجانبي",
            THAI_TH : "เปิดแถบด้านข้าง",
            LATIN_LA : "Aperi Sidebar",
            IRISH_GA : "Cuir an taobhchlár ar oscailt",
            BELARUSIAN_BE : "Адкрыць бакавую панэль",
            ODIA_OR : "ପାଇଁ ପଟାଖାଣା ଖୋଲନ୍ତୁ",
            FILIPINO_TL : "Buksan ang Sidebar",
        }

        s.Enter_key = {
            ENGLISH_EN : "Enter key",
            JAPANESE_JA : "エンターキー",
            PORTUGUES_PT : "Tecla Enter",
            DEUTSCH_DE : "Eingabetaste",
            FRANCAIS_FR : "Touche Entrée",
            PERSIAN_FA : "کلید وارد کردن",
            RUSSIAN_RU : "Клавиша Ввод",
            ESPANOL_ES : "Tecla Enter",
            TIENG_VIET_VI : "Phím Enter",
            # ---------
            AFRIKAANS_AF : "Druk sleutel",
            BAHASA_MELAYU_MS : "Kunci Enter",
            CATALA_CA : "Tecla Enter",
            DANSK_DA : "Enter-tast",
            EESTI_ET : "Enter-klahv",
            ESPERANTO_EO : "Eniga klavo",
            EUSKARA_EU : "Sakatu tekla",
            GALEGO_GL : "Tecla Enter",
            HRVATSKI_HR : "Tipka Enter",
            ITALIANO_IT : "Tasto Invio",
            LO_JBOBAU_JBO : "Enter key",
            LENGA_DOC_OC : "Tecla Enter",
            MAGYAR_HU : "Enter billentyű",
            NEDERLANDS_NL : "Enter-toets",
            NORSK_NB : "Enter-tast",
            POLSKI_PL : "Klawisz Enter",
            ROMANA_RO : "Tasta Enter",
            SLOVENCINA_SK : "Klávesa Enter",
            SLOVENSCINA_SL : "Tipka Enter",
            SUOMI_FI : "Enter-näppäin",
            SVENSKA_SV : "Enter-tangent",
            TURKCE_TR : "Enter tuşu",
            SIMPLIFIED_CHINESE_ZH : "回车键",
            KOREAN_KO : "엔터 키",
            CESTINA_CS : "Enter klávesa",
            HELLENIC_EL : "Πλήκτρο Enter",
            BULGARIAN_BG : "Бутон Въведи",
            MONGOL_MN : "Оруулах товч",
            SERBIAN_SR : "Enter taster",
            UKRAINIAN_UK : "Клавіша Ввід",
            ARMENIAN_HY : "Մուտքագրել ստորակետը",
            HEBREW_HE : "מקש Enter",
            ARABIC_AR : "مفتاح الدخول",
            THAI_TH : "ปุ่ม Enter",
            LATIN_LA : "Clavis Enter",
            IRISH_GA : "Eochair Iontrála",
            BELARUSIAN_BE : "Ключ Увядзіце",
            ODIA_OR : "ଏଣ୍ଟର କୀ",
            FILIPINO_TL : "Pindutin ang Enter",
        }


        s.Translate = {
        ENGLISH_EN : "Translate",
        JAPANESE_JA : "翻訳",
        PORTUGUES_PT : "Traduzir",
        DEUTSCH_DE : "Übersetzen",
        FRANCAIS_FR : "Traduire",
        PERSIAN_FA : "ترجمه",
        RUSSIAN_RU : "Перевести",
        ESPANOL_ES : "Traducir",
        TIENG_VIET_VI : "Dịch",
        # ---------
        AFRIKAANS_AF : "Vertaal",
        BAHASA_MELAYU_MS : "Terjemahkan",
        CATALA_CA : "Traduir",
        DANSK_DA : "Oversæt",
        EESTI_ET : "Tõlgi",
        ESPERANTO_EO : "Traduki",
        EUSKARA_EU : "Itzuli",
        GALEGO_GL : "Traducir",
        HRVATSKI_HR : "Prevesti",
        ITALIANO_IT : "Traduci",
        LO_JBOBAU_JBO : "Translate",
        LENGA_DOC_OC : "Traduire",
        MAGYAR_HU : "Fordítás",
        NEDERLANDS_NL : "Vertalen",
        NORSK_NB : "Oversett",
        POLSKI_PL : "Tłumaczyć",
        ROMANA_RO : "Traduce",
        SLOVENCINA_SK : "Preložiť",
        SLOVENSCINA_SL : "Prevesti",
        SUOMI_FI : "Käännä",
        SVENSKA_SV : "Översätt",
        TURKCE_TR : "Çevir",
        SIMPLIFIED_CHINESE_ZH : "翻译",
        KOREAN_KO : "번역",
        CESTINA_CS : "Přeložit",
        HELLENIC_EL : "Μετάφραση",
        BULGARIAN_BG : "Превеждам",
        MONGOL_MN : "Орчуулах",
        SERBIAN_SR : "Превести",
        UKRAINIAN_UK : "Перекласти",
        ARMENIAN_HY : "Թարգմանել",
        HEBREW_HE : "תרגם",
        ARABIC_AR : "ترجمة",
        THAI_TH : "แปล",
        LATIN_LA : "Transferre",
        IRISH_GA : "Aistriú",
        BELARUSIAN_BE : "Перакладаць",
        ODIA_OR : "ଅନୁବାଦ କରନ୍ତୁ",
        FILIPINO_TL : "Isalin",
        }



        s.Prefix = {
            ENGLISH_EN: "Prefix",
            JAPANESE_JA: "接頭辞",
            PORTUGUES_PT: "Prefixo",
            DEUTSCH_DE: "Präfix",
            FRANCAIS_FR: "Préfixe",
            PERSIAN_FA: "پیشوند",
            RUSSIAN_RU: "Префикс",
            ESPANOL_ES: "Prefijo",
            TIENG_VIET_VI: "Tiền tố",
            AFRIKAANS_AF: "Voorvoegsel",
            BAHASA_MELAYU_MS: "Awalan",
            CATALA_CA: "Prefix",
            DANSK_DA: "Præfiks",
            EESTI_ET: "Eesliide",
            ESPERANTO_EO: "Prefikso",
            EUSKARA_EU: "Aurreko",
            GALEGO_GL: "Prefixo",
            HRVATSKI_HR: "Prefiks",
            ITALIANO_IT: "Prefisso",
            LO_JBOBAU_JBO: "Prefix",
            LENGA_DOC_OC: "Préfixe",
            MAGYAR_HU: "Előtag",
            NEDERLANDS_NL: "Voorvoegsel",
            NORSK_NB: "Prefiks",
            POLSKI_PL: "Prefiks",
            ROMANA_RO: "Prefix",
            SLOVENCINA_SK: "Predpona",
            SLOVENSCINA_SL: "Predpona",
            SUOMI_FI: "Etuliite",
            SVENSKA_SV: "Prefix",
            TURKCE_TR: "Önek",
            SIMPLIFIED_CHINESE_ZH: "前缀",
            KOREAN_KO: "접두사",
            CESTINA_CS: "Předpona",
            HELLENIC_EL: "Πρόθεμα",
            BULGARIAN_BG: "Приставка",
            MONGOL_MN: "Угтвар",
            SERBIAN_SR: "Префикс",
            UKRAINIAN_UK: "Префікс",
            ARMENIAN_HY: "Նախաբառ",
            HEBREW_HE: "קידומת",
            ARABIC_AR: "بادئة",
            THAI_TH: "คำนำหน้า",
            LATIN_LA: "Prefixum",
            IRISH_GA: "Réamhfhocal",
            BELARUSIAN_BE: "Прэфікс",
            ODIA_OR: "ପୂର୍ବପଦ",
            FILIPINO_TL: "Unlapi",
        }

        s.check_box_tooltip = {
            ENGLISH_EN: "Automatically send default prompt after show card answer",
            JAPANESE_JA: "ｶｰﾄﾞの答えを表示した後にﾃﾞﾌｫﾙﾄのﾌﾟﾛﾝﾌﾟﾄを自動的に送信します",
            PORTUGUES_PT: "Enviar automaticamente o prompt padrão após mostrar a resposta do cartão",
            DEUTSCH_DE: "Automatisch den Standard-Prompt nach der Anzeige der Kartenantwort senden",
            FRANCAIS_FR: "Envoyer automatiquement le message par défaut après avoir affiché la réponse de la carte",
            PERSIAN_FA: "پس از نمایش پاسخ کارت، به طور خودکار پیام پیش فرض را ارسال کنید",
            RUSSIAN_RU: "Автоматически отправлять стандартное сообщение после показа ответа на карточку",
            ESPANOL_ES: "Enviar automáticamente el mensaje predeterminado después de mostrar la respuesta de la tarjeta",
            TIENG_VIET_VI: "Tự động gửi thông báo mặc định sau khi hiển thị câu trả lời của thẻ",

            AFRIKAANS_AF: "Voer outomaties die verstek-prompt in nadat die kaartantwoord gewys is",
            BAHASA_MELAYU_MS: "Hantar secara automatik prompt lalai selepas menunjukkan jawapan kad",
            CATALA_CA: "Enviar automàticament el missatge predeterminat després de mostrar la resposta de la targeta",
            DANSK_DA: "Send automatisk standardprompten efter visning af kortets svar",
            EESTI_ET: "Saada vaikimisi teade pärast kaardi vastuse kuvamist automaatselt",
            ESPERANTO_EO: "Sendi aŭtomate la defaŭltan mesaĝon post montri la respondon de la karto",
            EUSKARA_EU: "Karta erantzunaren aurkezpenaren ondoren, mezu lehenetsia automatikoki bidali",
            GALEGO_GL: "Enviar automaticamente a mensaxe predeterminada despois de mostrar a resposta da tarxeta",
            HRVATSKI_HR: "Automatski pošalji zadani upit nakon prikazivanja odgovora na kartici",
            ITALIANO_IT: "Invia automaticamente il prompt predefinito dopo aver mostrato la risposta della carta",
            LO_JBOBAU_JBO: "Sendu la defaŭltan mesaĝon aŭtomate post montri la respondon de la karto",
            LENGA_DOC_OC: "Envoi automatique du message par défaut après avoir affiché la réponse de la carte",
            MAGYAR_HU: "Automatikusan küldje el az alapértelmezett üzenetet a kártya válasza után",
            NEDERLANDS_NL: "Stuur automatisch het standaardbericht na het tonen van het antwoord op de kaart",
            NORSK_NB: "Send automatisk standardmelding etter å ha vist svaret på kortet",
            POLSKI_PL: "Automatycznie wysyłaj domyślną wiadomość po pokazaniu odpowiedzi na karcie",
            ROMANA_RO: "Trimite automat mesajul implicit după afișarea răspunsului cărții",
            SLOVENCINA_SK: "Automaticky po zobrazení odpovede na kartu odoslať predvolenú správu",
            SLOVENSCINA_SL: "Samodejno pošlji privzeto sporočilo po prikazu odgovora na kartici",
            SUOMI_FI: "Lähetä oletusviesti automaattisesti kortin vastauksen näyttämisen jälkeen",
            SVENSKA_SV: "Skicka automatiskt standardmeddelandet efter att ha visat kortets svar",
            TURKCE_TR: "Kart cevabı gösterildikten sonra varsayılan mesajı otomatik olarak gönder",
            SIMPLIFIED_CHINESE_ZH: "显示卡片答案后自动发送默认提示",
            KOREAN_KO: "카드 답변을 표시한 후에 기본 프롬프트를 자동으로 전송합니다",
            CESTINA_CS: "Automaticky odeslat výchozí zprávu po zobrazení odpovědi na kartě",
            HELLENIC_EL: "Αποστολή αυτόματου προεπιλεγμένου μηνύματος μετά την εμφάνιση της απάντησης της κάρτας",
            BULGARIAN_BG: "Изпращане на автоматично съобщение след показване на отговора на картата",
            MONGOL_MN: "Картын хариултыг харуулж дараахь дефаулт мессежийг автоматаар илгээнэ",
            SERBIAN_SR: "Аутоматски пошаљите подразумевану поруку након приказивања одговора на картици",
            UKRAINIAN_UK: "Автоматично надсилайте стандартне повідомлення після показу відповіді на картці",
            ARMENIAN_HY: "Ստանալ ավտոմատ նախաբառը ցուցադրվելուց հետո ուղարկել ստանալու համար",
            HEBREW_HE: "שלח אוטומטית את ההודעה המוגדרת מראש לאחר הצגת תשובת הכרטיס",
            ARABIC_AR: "إرسال الرسالة الافتراضية تلقائيًا بعد عرض إجابة البطاقة",
            THAI_TH: "ส่งข้อความเริ่มต้นโดยอัตโนมัติหลังจากแสดงคำตอบของการ์ด",
            LATIN_LA: "Automatice mittere nuntium praedefinitum post ostendere responsionem chartae",
            IRISH_GA: "Cuir teachtaireacht réamhshocraithe ar aghaidh go huathoibríoch tar éis freagra an chárta a thaispeáint",
            BELARUSIAN_BE: "Аўтаматычна даслаць стандартнае паведамленне пасля паказу адказу на картку",
            ODIA_OR: "କାର୍ଡ ଉତ୍ତର ଦେଖାଇବାରେ ପୂର୍ବନିର୍ଧାରିତ ପ୍ରମ୍ପ୍ଟ ପରିଷ୍କରଣ ପରିଷ୍କରଣ ପଠାନ୍ତୁ",
            FILIPINO_TL: "Ipadala nang awtomatiko ang default na prompt matapos ipakita ang sagot ng card",
        }

        s.template = {
        ENGLISH_EN : "",
        JAPANESE_JA : "",
        PORTUGUES_PT : "",
        DEUTSCH_DE : "",
        FRANCAIS_FR : "",
        PERSIAN_FA : "",
        RUSSIAN_RU : "",
        ESPANOL_ES : "",
        TIENG_VIET_VI : "",
        # ---------
        AFRIKAANS_AF : "",
        BAHASA_MELAYU_MS : "",
        CATALA_CA : "",
        DANSK_DA : "",
        EESTI_ET : "",
        ESPERANTO_EO : "",
        EUSKARA_EU : "",
        GALEGO_GL : "",
        HRVATSKI_HR : "",
        ITALIANO_IT : "",
        LO_JBOBAU_JBO : "",
        LENGA_DOC_OC : "",
        MAGYAR_HU : "",
        NEDERLANDS_NL : "",
        NORSK_NB : "",
        POLSKI_PL : "",
        ROMANA_RO : "",
        SLOVENCINA_SK : "",
        SLOVENSCINA_SL : "",
        SUOMI_FI : "",
        SVENSKA_SV : "",
        TURKCE_TR : "",
        SIMPLIFIED_CHINESE_ZH : "",
        KOREAN_KO : "",
        CESTINA_CS : "",
        HELLENIC_EL : "",
        BULGARIAN_BG : "",
        MONGOL_MN : "",
        SERBIAN_SR : "",
        UKRAINIAN_UK : "",
        ARMENIAN_HY : "",
        HEBREW_HE : "",
        ARABIC_AR : "",
        THAI_TH : "",
        LATIN_LA : "",
        IRISH_GA : "",
        BELARUSIAN_BE : "",
        ODIA_OR : "",
        FILIPINO_TL : "",
        }

        s.lang = {
        ENGLISH_EN : "English",
        JAPANESE_JA : "Japanese",
        PORTUGUES_PT : "Portugues",
        DEUTSCH_DE : "Deutsch",
        FRANCAIS_FR : "Francais",
        PERSIAN_FA : "Persian",
        RUSSIAN_RU : "Russian",
        ESPANOL_ES : "Espanol",
        TIENG_VIET_VI : "Tieng Viet",
        # ---------
        AFRIKAANS_AF : "Afrikaans",
        BAHASA_MELAYU_MS : "Bahasa_Melayu",
        CATALA_CA : "Catala",
        DANSK_DA : "Dansk",
        EESTI_ET : "Eesti",
        ESPERANTO_EO : "Esperanto",
        EUSKARA_EU : "Euskara",
        GALEGO_GL : "Galego",
        HRVATSKI_HR : "Hrvatski",
        ITALIANO_IT : "Italiano",
        LO_JBOBAU_JBO : "Lo_Jbobau",
        LENGA_DOC_OC : "Lenga_Doc",
        MAGYAR_HU : "Magyar",
        NEDERLANDS_NL : "Nederlands",
        NORSK_NB : "Norsk",
        POLSKI_PL : "Polski",
        ROMANA_RO : "Romana",
        SLOVENCINA_SK : "Slovencina",
        SLOVENSCINA_SL : "Slovenscina",
        SUOMI_FI : "Suomi",
        SVENSKA_SV : "Svenska",
        TURKCE_TR : "Turkce",
        SIMPLIFIED_CHINESE_ZH : "Chinese",
        KOREAN_KO : "Korean",
        CESTINA_CS : "Cestina",
        HELLENIC_EL : "Hellenic",
        BULGARIAN_BG : "Bulgarian",
        MONGOL_MN : "Mongol",
        SERBIAN_SR : "Serbian",
        UKRAINIAN_UK : "Ukrainian",
        ARMENIAN_HY : "Armenian",
        HEBREW_HE : "Hebrew",
        ARABIC_AR : "Arabic",
        THAI_TH : "Thai",
        LATIN_LA : "Latin",
        IRISH_GA : "Irish",
        BELARUSIAN_BE : "Belarusian",
        ODIA_OR : "Odia",
        FILIPINO_TL : "Filipino",
        }


    # template = {
    # ENGLISH_EN: "",
    # JAPANESE_JA: "",
    # PORTUGUES_PT: "",
    # DEUTSCH_DE: "",
    # FRANCAIS_FR: "",
    # PERSIAN_FA: "",
    # RUSSIAN_RU: "",
    # ESPANOL_ES: "",
    # TIENG_VIET_VI: "",
    # }

    # check_box_tooltip = {
    # ENGLISH_EN: "Automatically send default prompt after show card answer",
    # JAPANESE_JA: "ｶｰﾄﾞの答えを表示した後にﾃﾞﾌｫﾙﾄのﾌﾟﾛﾝﾌﾟﾄを自動的に送信します",
    # PORTUGUES_PT: "Enviar automaticamente o prompt padrão após a resposta do cartão",
    # DEUTSCH_DE: "Standardaufforderung automatisch senden, nachdem die Kartenantwort angezeigt wurde",
    # FRANCAIS_FR: "Envoyer automatiquement l'invite par défaut après la réponse de la carte",
    # PERSIAN_FA: "پس از نمایش پاسخ کارت ، به طور خودکار پیش فرض را ارسال کنید",
    # RUSSIAN_RU: "Автоматически отправлять стандартный запрос после ответа на карточку",
    # ESPANOL_ES: "Enviar automáticamente el mensaje predeterminado después de mostrar la respuesta de la tarjeta",
    # TIENG_VIET_VI: "Tự động gửi lời nhắc mặc định sau khi hiển thị câu trả lời thẻ",
    # }


    def __getattribute__(self, name):
        attr = super().__getattribute__(name)
        global current_lang
        if isinstance(attr, dict):
            current_lang = current_lang.split('-')[0]
            print(current_lang)
            return attr.get(current_lang)
        else:
            return super().__getattribute__(name)


shige_tr = LanguageManager()
